version: 0.2
phases:
  build:
    commands:
      - echo Installing source PHP dependencies...
      - composer install --ignore-platform-reqs
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
